find_package(OpenCV REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})
# find_package(kaylordut REQUIRED)
find_package(Threads REQUIRED)
link_directories(${PROJECT_SOURCE_DIR}/lib)
file(GLOB SRC "*.cpp")
file(GLOB MOBILE_SAM_SRC "mobilesam/*.cc" "mobilesam/*.c")
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/mobilesam)
add_library(yolov8-utils ${SRC} ${MOBILE_SAM_SRC})
target_link_libraries(yolov8-utils PUBLIC ${OpenCV_LIBS} rknnrt rga Threads::Threads)
